# Generated by Django 4.0.4 on 2022-06-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_symptom', to='api.symptom')),
            ],
            options={
                'verbose_name': 'Симптом для женщин',
                'verbose_name_plural': 'Симптомы для женщин',
            },
        ),
        migrations.CreateModel(
            name='MenSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men_symptom', to='api.symptom')),
            ],
            options={
                'verbose_name': 'Симптом для мужчин',
                'verbose_name_plural': 'Симптомы для мужчин',
            },
        ),
        migrations.CreateModel(
            name='ChildSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_symptom', to='api.symptom')),
            ],
            options={
                'verbose_name': 'Симптом для детей',
                'verbose_name_plural': 'Симптомы для детей',
            },
        ),
        migrations.CreateModel(
            name='AdultSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adult_symptom', to='api.symptom')),
            ],
            options={
                'verbose_name': 'Симптом для взрослых',
                'verbose_name_plural': 'Симптомы для взрослых',
            },
        ),
    ]
