# Generated by Django 4.0.4 on 2022-06-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('order_id', models.CharField(max_length=255)),
                ('order_email', models.CharField(max_length=255, null=True)),
                ('order_phone', models.CharField(max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='CREATED', max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
            ],
        ),
    ]
