# Generated by Django 4.0.4 on 2022-06-07 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
