# Generated by Django 4.0.4 on 2022-06-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctorschedule_can_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.useranalysis'),
        ),
        migrations.AlterField(
            model_name='request',
            name='conclusion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='doctor_conclusion',
            field=models.TextField(null=True),
        ),
    ]
