# Generated by Django 4.0.4 on 2022-06-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_order_id_alter_request_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='doctor_schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.doctorschedule'),
            preserve_default=False,
        ),
    ]
