# Generated by Django 4.0.4 on 2022-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_request_doctor_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='meeting_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
