version: "3.9"

services:
  web:
    container_name: telemedicine-api
    build:
      context: ../
      dockerfile: .build/python/Dockerfile
    env_file:
      - .env
    ports:
      - ${EXTERNAL_PORT}:8000

  db:
    image: postgres:13.0-alpine
    container_name: telemedicine-db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${DB_HOST_PATH}:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}