version: '3.9'

services:
  web:
    build:
      target: prod
    volumes:
      - ${MEDIA_FILES_PATH}:/home/app/web/mediafiles
      - ${STATIC_FILES_PATH}:/home/app/web/staticfiles
    networks:
      - app-network

  nginx:
    build: nginx
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html
      - ${STATIC_FILES_PATH}:/home/app/web/staticfiles
      - ${MEDIA_FILES_PATH}:/home/app/web/mediafiles
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - ${EXTERNAL_NGINX_PORT}:80
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ${WEB_ROOT_PATH}:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email biba4756@gmail.com --agree-tos --no-eff-email --staging -d server.online-medicine.kz  -d www.server.online-medicine.kz

volumes:
  certbot-etc:
  certbot-var:
  static_volume:
  media_volume:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/diploma-back/
      o: bind

networks:
  app-network:
    driver: bridge