version: '3.9'

services:
  web:
    build:
      target: dev
    volumes:
      - ..:/app
    depends_on:
      - db

  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: