version: '3.9'

services:
  api:
    build:
      target: dev
      context: ../backend
      dockerfile: ../.deploy/build/api/Dockerfile
    volumes:
      - ../backend:/app
    depends_on:
      - db

  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ../frontend
      dockerfile: ../.deploy/build/frontend/Dockerfile
    volumes:
      - ../frontend:/app

volumes:
  postgres_data: