# Generated by Django 4.0.4 on 2022-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_doctor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
