# Generated by Django 4.0.4 on 2022-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_alter_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='phone',
            field=models.CharField(default='87080000000', max_length=255),
        ),
    ]
